
package cn.edu.nju.soa.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T19:06:38.582+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "NotFoundFault", targetNamespace = "http://jw.nju.edu.cn/schema")
public class CourseIdFault extends Exception {

    private cn.edu.nju.soa.model.NotFoundType notFoundFault;

    public CourseIdFault() {
        super();
    }

    public CourseIdFault(String message) {
        super(message);
    }

    public CourseIdFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CourseIdFault(String message, cn.edu.nju.soa.model.NotFoundType notFoundFault) {
        super(message);
        this.notFoundFault = notFoundFault;
    }

    public CourseIdFault(String message, cn.edu.nju.soa.model.NotFoundType notFoundFault, Throwable cause) {
        super(message, cause);
        this.notFoundFault = notFoundFault;
    }

    public cn.edu.nju.soa.model.NotFoundType getFaultInfo() {
        return this.notFoundFault;
    }
}
